from pathlib import Path
import json
root=Path(__file__).parent
sections=[
('city','01-city','LOCAL BUSINESS. BIG POSSIBILITIES.','သင့်လုပ်ငန်းကို လူပိုသိစေမယ်။','Content, social media & live commerce for Myanmar businesses.','ဝန်ဆောင်မှုများ ကြည့်ရန်','services','left'),
('content','02-content','CONTENT THAT CONNECTS.','သင့်အမှတ်တံဆိပ်အတွက် ထိမိတဲ့ Content။','Photos, short videos and stories for Facebook, Instagram & TikTok.','လုပ်ငန်းများ ကြည့်ရန်','hotel','right'),
('hotel','03-hotel','TURN VIEWS INTO VISITS.','သင့်ဟိုတယ်ကို ရွေးချယ်ချင်လာစေမယ်။','Show the stay. Inspire the next booking.','Plan ရွေးရန်','services','left'),
('food','04-food','MAKE THEM WANT A TASTE.','မြင်တာနဲ့ လာစားချင်စေမယ်။','Food stories that bring your restaurant to life.','Plan ရွေးရန်','services','right'),
('seller','05-seller','SMALL SHOP. MORE POSSIBILITIES.','သင့်ဆိုင်ကို ပိုလူသိစေမယ်။','Product content, shop stories and everyday social support.','Plan ရွေးရန်','services','left'),
('craft','06-craft','LOCAL CRAFT. LASTING IMPRESSION.','လက်ရာတိုင်းမှာ ပြောစရာရှိတယ်။','Tell the story behind the hands and the craft.','Plan ရွေးရန်','services','right'),
('brand','07-brand','BUILD A BRAND THEY REMEMBER.','သင့်အမှတ်တံဆိပ်ကို မှတ်မိနေစေမယ်။','Distinctive visuals. A consistent voice.','Plan ရွေးရန်','services','left'),
('live','08-live','GO LIVE. GET CLOSER.','Live မှာ ဖောက်သည်နဲ့ ပိုနီးစပ်စေမယ်။','Live planning, product demos and audience interaction.','Live Plan ကြည့်ရန်','services','right dark'),
('services','09-team','YOUR NEXT CHAPTER STARTS HERE.','သင့်လုပ်ငန်းနဲ့ ကိုက်ညီတဲ့ Plan။','Choose your support. We shape the details together.','Plan များ နှိုင်းယှဉ်ရန်','plans','left'),
('contact','10-evening','LET’S GROW, TOGETHER.','သင့်လုပ်ငန်းအကြောင်း ပြောပြပါ။','Find us on Facebook: Business Growth Myanmar.','Page နာမည် ကူးယူရန်','copy','right dark')]
(root/'content.json').write_text(json.dumps(sections,ensure_ascii=False,indent=2))
head='''<!doctype html><html lang="my"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#1237c7"><title>Business Growth Myanmar — Content & Social Media</title><meta name="description" content="Content creation, social media management and live commerce for local businesses in Myanmar."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Noto+Sans+Myanmar:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#city">Skip to content</a><header><a class="brand" href="#city" aria-label="Business Growth Myanmar home"><span class="monogram">bgm<span>↗</span></span><span>BUSINESS GROWTH<br>MYANMAR</span></a><nav aria-label="Main navigation"><a href="#hotel">Industries</a><a href="#plans">Plans</a><a class="nav-contact" href="#contact">စကားပြောကြမယ် <span>↗</span></a></nav></header><aside class="rail" aria-label="Section navigation">'''+''.join(f'<a href="#{s[0]}" aria-label="{s[0]}" title="{s[0]}">{i+1:02}</a>' for i,s in enumerate(sections))+'''</aside><main>'''
parts=[]
for i,(sid,img,kicker,title,desc,cta,target,side) in enumerate(sections):
    button=f'<button class="cta copy-page">{cta} <span>↗</span></button>' if target=='copy' else f'<a class="cta" href="#{target}">{cta} <span>↗</span></a>'
    parts.append(f'''<section id="{sid}" class="hero {side}" data-index="{i}" aria-labelledby="title-{sid}"><div class="visual"><img src="assets/{img}.png" alt="{['Campaign planning with a Yangon business owner','Collaborative social content planning','Hotel content shoot','Restaurant food photography','Local seller packing products','Learning about local textile craftsmanship','Styling a local brand product shoot','Demonstrating a product during a livestream','Agency team discussing a campaign','Reviewing campaign footage with a client'][i]}" {'fetchpriority="high"' if i==0 else 'loading="lazy"'} width="1672" height="941"><video muted playsinline loop preload="none" aria-hidden="true"></video></div><div class="shade"></div><div class="hero-copy"><p class="eyebrow">{i+1:02} / {kicker}</p><h1 id="title-{sid}">{title}</h1><p class="desc" lang="en">{desc}</p>{button}</div><div class="section-bottom"><span>{['YANGON, MYANMAR','CREATE · CONNECT · GROW','HOSPITALITY','FOOD & BEVERAGE','LOCAL SELLERS','HANDMADE & HERITAGE','LOCAL BRANDS','LIVE COMMERCE','YOUR GROWTH TEAM','BUSINESS GROWTH MYANMAR'][i]}</span><span>{'SCROLL TO EXPLORE ↓' if i==0 else 'FACEBOOK · INSTAGRAM · TIKTOK'}</span></div></section>''')
    if sid=='services':
        parts.append('''<section class="plans" id="plans" aria-labelledby="plans-title"><div class="plans-intro"><p class="eyebrow">SUPPORT THAT FITS YOUR BUSINESS</p><h2 id="plans-title">သင့်အတွက် ဘယ် Plan လဲ။</h2><p>လုပ်ငန်းလိုအပ်ချက်အလိုက် ဝန်ဆောင်မှုများကို ညှိနှိုင်းနိုင်ပါတယ်။</p></div><div class="plan-grid"><article><p class="plan-number">01 / CREATE</p><h3>Content Studio</h3><p>အမှတ်တံဆိပ်ကို ထင်ရှားစေဖို့။</p><ul><li>Content planning</li><li>Product & business photography</li><li>Short-form video editing</li><li>Myanmar & English captions</li></ul><a href="#contact">ဒီ Plan ကို ဆွေးနွေးရန် ↗</a></article><article class="featured"><p class="plan-number">02 / MANAGE</p><h3>Social Management</h3><p>နေ့စဉ် Social Media အတွက်။</p><ul><li>Content Studio support</li><li>Monthly content calendar</li><li>Publishing & community replies</li><li>Monthly performance review</li></ul><a href="#contact">ဒီ Plan ကို ဆွေးနွေးရန် ↗</a></article><article><p class="plan-number">03 / CONNECT</p><h3>Live Commerce</h3><p>Live အစမှ အဆုံးအထိ အတူရှိမယ်။</p><ul><li>Live session planning</li><li>Product demo preparation</li><li>Livestream production support</li><li>Audience & enquiry coordination</li></ul><a href="#contact">ဒီ Plan ကို ဆွေးနွေးရန် ↗</a></article></div><p class="plan-note">Scope & pricing tailored to your business. Advertising spend quoted separately.</p></section>''')
end='''</main><footer><strong>Business Growth Myanmar</strong><span>Content. Community. Commerce.</span><a href="#city">Back to top ↑</a></footer><div id="toast" role="status" aria-live="polite"></div><dialog id="copy-dialog"><h2>Find our Facebook Page</h2><p>Business Growth Myanmar</p><p>ဒီနာမည်ကို Facebook မှာ ရှာနိုင်ပါတယ်။</p><button id="close-dialog">Close</button></dialog><script src="media.js"></script><script src="app.js"></script></body></html>'''
(root/'dist/index.html').write_text(head+''.join(parts)+end)
