from pathlib import Path
import json
root=Path(__file__).parent
rows=json.loads((root/'content.json').read_text())
def media(i,klass=''):
 r=rows[i]
 return f'<div class="media {klass}" data-media="{r[0]}"><img src="assets/{r[1]}.webp" width="1672" height="941" alt="{r[2].title()} — Business Growth Myanmar campaign illustration" {"fetchpriority=high" if i==0 else "loading=lazy"}><video muted playsinline loop preload="none" aria-hidden="true"></video></div>'
def label(n,title):return f'<div class="section-label"><span>({n:02})</span><span>{title}</span></div>'
html='''<!doctype html><html lang="my"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="favicon.svg" type="image/svg+xml"><meta name="theme-color" content="#f2f0e9"><title>Business Growth Myanmar — Grow local.</title><meta name="description" content="Content, social media management and live commerce for local businesses in Myanmar."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=Instrument+Serif:ital@0;1&family=Noto+Sans+Myanmar:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css?v=2"></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="wordmark" href="#city" aria-label="Business Growth Myanmar home">Business Growth<span>Myanmar<span class="brand-dot">↗</span></span></a><span class="header-note">INDEPENDENT THINKING.<br>LOCAL UNDERSTANDING.</span><nav aria-label="Main navigation"><a href="#hotel">Industries</a><a href="#services">Services</a><a href="#contact" class="nav-contact">Let’s talk <span>↗</span></a></nav></header><main id="main">
'''
html+='''<section id="city" class="opening chapter" aria-labelledby="opening-title"><div class="opening-top"><div><p class="micro">CONTENT / SOCIAL / COMMERCE</p><h1 id="opening-title">GROW<span class="local">LOCAL<span class="period">.</span></span></h1></div><div class="opening-aside"><p class="my opening-my">သင့်လုပ်ငန်းကို<br>လူပိုသိစေမယ်။</p><p class="intro-text">We turn local stories into<br>brands people connect with.</p><a class="round-link" href="#content" aria-label="Explore our approach"><span>EXPLORE</span><b>↓</b></a></div></div><div class="opening-image">'''+media(0)+'''<div class="image-label"><span>ROOTED IN YANGON.</span><span>READY FOR WHAT’S NEXT.</span></div></div><div class="opening-bottom"><span>BUSINESS GROWTH MYANMAR</span><span>Facebook / Instagram / TikTok</span><span>SCROLL TO DISCOVER ↓</span></div></section>'''
html+='<section id="content" class="content-story chapter">'+label(2,'THE WAY WE WORK')+'''<div class="content-grid"><div class="content-copy"><h2>Good stories.<br><em>Real connection.</em></h2><p class="my">သင့်အမှတ်တံဆိပ်အတွက်<br>ထိမိတဲ့ Content။</p><p>From the first idea to the everyday post.<br>We create, publish and keep the conversation going.</p><div class="service-words"><span>01 / Content creation</span><span>02 / Social media management</span><span>03 / Live commerce</span></div></div><div class="content-image">'''+media(1)+'''<p class="photo-note">Ideas become images. Images start conversations.</p></div></div><div class="industry-intro"><p class="micro">MADE FOR THE BUSINESSES AROUND US</p><h2>Your world.<br><em>Our next story.</em></h2><p class="my">လုပ်ငန်းမျိုးစုံအတွက် ဖန်တီးပေးမယ်။</p></div></section>'''
titles=[('HOSPITALITY','A stay worth','discovering.','Room stories. Property films. Booking enquiries.'),('FOOD & BEVERAGE','From the feed','to your table.','Food photography. Short videos. Restaurant stories.'),('LOCAL SELLERS','Small shop.','Wider world.','Product content. Shop stories. Social support.'),('CRAFT & HERITAGE','Made by hand.','Seen by more.','Craft stories. Product detail. Local identity.'),('LOCAL BRANDS','Stand out.','Stay remembered.','Campaign visuals. Brand voice. Everyday consistency.')]
html+='<div class="industry-sequence">'
for i,(cat,t1,t2,desc) in enumerate(titles,2):
 r=rows[i]
 html+=f'<span id="{r[0]}" class="scene-anchor" aria-hidden="true"></span><section id="scene-{r[0]}" class="scene chapter scene-{i}" aria-labelledby="heading-{r[0]}"><div class="scene-top"><span>({i+1:02})</span><span>{cat}</span><span>BUSINESS IN FOCUS</span></div>'+media(i)+f'<div class="scene-caption"><h2 id="heading-{r[0]}">{t1}<br><em>{t2}</em></h2><div><p class="my">{r[3]}</p><p>{desc}</p></div><a href="#services" class="scene-arrow" aria-label="Explore services for {cat.lower()}">↗</a></div></section>'
html+='</div>'
html+='<section id="live" class="live chapter">'+label(8,'LIVE COMMERCE')+'''<div class="live-heading"><h2>In the moment.<br><em>Closer to your customers.</em></h2><p class="my">Live မှာ ဖောက်သည်နဲ့<br>ပိုနီးစပ်စေမယ်။</p></div>'''+media(7)+'''<div class="live-bottom"><span>PLAN THE SESSION.</span><span>SHOW THE PRODUCT.</span><span>START A CONVERSATION.</span></div></section>'''
html+='<section id="services" class="services chapter">'+label(9,'A TEAM BEHIND YOUR BUSINESS')+'''<div class="services-heading"><h2>Let’s make<br><em>growth a habit.</em></h2><div><p class="my">သင့်လုပ်ငန်းနဲ့<br>ကိုက်ညီတဲ့ Plan။</p><p>One project or ongoing support.<br>Choose where we start.</p></div></div><div class="services-layout"><div class="team-image">'''+media(8)+'''<p class="photo-note">Create together. Keep getting better.</p></div><div class="plan-list" id="plans">'''
plans=[('01','Content Studio','အမှတ်တံဆိပ်ကို ထင်ရှားစေဖို့။',['Content planning','Product & business photography','Short-form video editing','Myanmar & English captions']),('02','Social Management','နေ့စဉ် Social Media အတွက်။',['Content Studio support','Monthly content calendar','Publishing & community replies','Monthly performance review']),('03','Live Commerce','Live အစမှ အဆုံးအထိ အတူရှိမယ်။',['Live session planning','Product demo preparation','Livestream production support','Audience & enquiry coordination'])]
for num,title,my,items in plans:
 html+=f'<details {"open" if num=="01" else ""}><summary><span class="plan-num">{num}</span><h3>{title}</h3><span class="expand" aria-hidden="true">+</span></summary><div class="plan-body"><p class="my">{my}</p><ul>'+''.join('<li>'+x+'</li>' for x in items)+f'</ul><a class="text-link" href="#contact" data-plan="{title}">ဒီ Plan ကို ဆွေးနွေးရန် <span>↗</span></a></div></details>'
html+='''<p class="plan-note">Scope & pricing shaped around your business.<br>Advertising spend quoted separately.</p></div></div></section>'''
html+='<section id="contact" class="contact chapter">'+label(10,'YOUR NEXT CHAPTER')+'''<div class="contact-grid"><div><p class="my">သင့်လုပ်ငန်းအကြောင်း ပြောပြပါ။</p><h2>BIG IDEAS.<br><em>Start here.</em></h2><p id="plan-interest" aria-live="polite"></p><div class="contact-actions"><p class="micro">FIND OUR FACEBOOK PAGE</p><p class="page-name">Business Growth Myanmar</p><button class="copy-page">Page နာမည် ကူးယူရန် <span>↗</span></button></div></div><div class="contact-image">'''+media(9)+'''</div></div><footer><a class="footer-brand" href="#city">Business Growth Myanmar <span>↗</span></a><div><span>YANGON, MYANMAR</span><span>Content / Social / Commerce</span><a href="#city">Back to top ↑</a></div><p class="image-disclosure">Campaign illustrations. Actual results vary by business.</p></footer></section></main><div class="chapter-progress" aria-hidden="true"><span id="chapter-num">01</span><div><i></i></div><span>10</span></div><div id="toast" role="status" aria-live="polite"></div><dialog id="copy-dialog"><h2>Find our Facebook Page</h2><p>Business Growth Myanmar</p><p class="my">ဒီနာမည်ကို Facebook မှာ ရှာနိုင်ပါတယ်။</p><button id="close-dialog">Close</button></dialog><script src="media.js"></script><script src="app.js?v=2"></script></body></html>'''
(root/'dist/index.html').write_text(html)
